### ISSUE TITLE
Example for two buttons

### ISSUE THREAD

**Issue by Teacher-Heiko** [LoganTraceur/LogansGreatButton#6]
Hi,

I am trying to figure out how to use more than one button with the library. Do you have an example?
The code below compiles, but what I want to do is that button1 and button2 have different behaviour in their callback functions.

#include <LogansGreatButton.h>

#define BUTTON_PIN 2
LogansGreatButton button1(BUTTON_PIN);
#define BUTTON_PIN 3
LogansGreatButton button2(BUTTON_PIN);

void setup() {
  Serial.begin(9600);
  Serial.println("Welcome to LogansGreatButton example!");

  button1.onActionPressed(onButtonActionPressed);
  button1.onPressShortRelease(onButtonPressShortRelease);
  button1.onPressLongStart(onButtonPressLongStart);
  button1.onPressLongRelease(onButtonPressLongRelease);
  button1.onHoldStart(onButtonHoldStart);
  button1.onHoldContinuous(onButtonHoldContinuous);
  button1.onHoldRelease(onButtonHoldRelease);

  button2.onActionPressed(onButtonActionPressed);
  button2.onPressShortRelease(onButtonPressShortRelease);
  button2.onPressLongStart(onButtonPressLongStart);
  button2.onPressLongRelease(onButtonPressLongRelease);
  button2.onHoldStart(onButtonHoldStart);
  button2.onHoldContinuous(onButtonHoldContinuous);
  button2.onHoldRelease(onButtonHoldRelease);
}

void loop() {
  button1.LOOPButtonController();
  button2.LOOPButtonController();
}

//_______________________________________________________________________________________________________________________________________________________________
// EXAMPLE
// -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// What the button does in different situations

void onButtonActionPressed()
{
  Serial.println();
  Serial.println("The button has been PRESSED. What will the future hold?");
}

void onButtonPressShortRelease()
{
  Serial.println("End of a SHORT Press");
}

void onButtonPressLongStart()
{
  Serial.println("Start of a LONG Press");
}

void onButtonPressLongRelease()
{
  Serial.println("End of a LONG Press");
}

void onButtonHoldStart()
{
  Serial.println("Start of a HOLD Press");
}

void onButtonHoldContinuous()
{
  Serial.println("The button is being held. This message will be resend continuously.");
}

void onButtonHoldRelease()
{
  Serial.println("End of a HOLD Press");
}

**Comment by LoganTraceur** [comment]
Hi,

You are very close. Because of the way callback functions work you need each callback function to have a unique name. I have added an example to the library on github now 🙂

[cid:db75fc5d-7943-479f-84e1-d0d94a17df47]
https://github.com/LoganTraceur/LogansGreatButton/tree/master/examples
I hope it works for you, Have a great day

Logan Krantz


________________________________
